### ISSUE TITLE
GitHub: saved replies dropdown no longer loads

### ISSUE THREAD

**Issue by jrfnl** [martok/palefill#100]
Seems to be something which changed in the last few days (as I remember adding a new saved reply from the dropdown last week).

When I click on the "Saved replies" button, the following non-descript and useless error shows up in the console:
![image](https://github.com/martok/palefill/assets/663378/bd460867-ac23-4b61-be26-ecd44686b28d)

**Comment by martok** [comment]
TIL: [`<dialog>` elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog). That's actually pretty useful, reminds me of something I wrote *checks git* 16 years ago 🤯 

May want to do that in the platform...

**Comment by AroKol78** [comment]
I don't know if it matters, but when I switch (`dom.dialog_element.enabled`) it, the the element examples work [<dialog> elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog)

**Comment by jrfnl** [comment]
I'll give `dom.dialog_element.enabled` a try and will let you know how I get on.

**Comment by jrfnl** [comment]
Hmm... sort of working, but not really...

![image](https://github.com/martok/palefill/assets/663378/32b87668-f438-403a-be35-edac0dc18886)

Only shows the first 8 saved replies (I have more), doesn't show the "add new saved reply", doesn't allow scrolling the list.

Error is gone from Console though and no new errors showing up (even though it doesn't work as it should).

**Comment by rofl0r** [comment]
probably equally annoying is that i can't close issues anymore. js log shows "ReferenceError: PerformanceObserver is not defined"

**Comment by jrfnl** [comment]
@rofl0r Cricky.. I hadn't noticed that yet (haven't had to close an issue in the last two days) That **IS** terrible design by GH... Seriously, what happened to the age-old wisdom of graceful degradation ? Don't they teach that anymore to kids nowadays ?

**Comment by jrfnl** [comment]
Just saw Palemoon 33.0.0 was released and installed that, but not seeing improvements on this issue. Was worth a try anyway ;-)

**Comment by rofl0r** [comment]
btw i was able to fix that with dom.enable_performance_observer. rubberduck debugging at its finest.

**Comment by AroKol78** [comment]
`dom.dialog_element.enabled` without this switch the account menu doesn't work and ...
if I switch it, it displays miracles

<details><summary>Screenshot_x2</summary>

![buggh0001](https://github.com/martok/palefill/assets/70756447/0d61e639-cbbf-4c70-9d79-1b9f7da16c5b)
![buggh0002](https://github.com/martok/palefill/assets/70756447/5d0b079c-e977-4f0e-b551-0a0c4b47d0b1)

</details>

**Comment by martok** [comment]
Fixed by PM 33.2, thanks to a lot of work by Moonchild 🎉
