### ISSUE TITLE
Gitlab search box not working

### ISSUE THREAD

**Issue by JAAnon** [martok/palefill#17]
Browser version: PM 31
Steps to reproduce: go to https://git.adelielinux.org/groups/adelie/-/issues
Expected behavior: I should see the "select project to create issue" and click the arrow on the right to open the search box.
Actual behavior: there is a spinning circle instead of "select project.." and clicking on the arrow has no effect.

**Comment by JAAnon** [comment]
Thanks so much 😊 I hope this feature could be implemented because github-wc-polyfill is still stuck, I think they are waiting for the next PM release.

**Comment by martok** [comment]
That was surprisingly easy. It's almost as if the third rewrite of the rule engine is actually as good and flexible as I wanted it :smile:
