### ISSUE TITLE
Fix www.virustotal.com (not really a polyfill)

### ISSUE THREAD

**Issue by RamonUnch** [martok/palefill#18]
Maybe this demand is slightly out of the scope of this plugin but given that many users that are using palemoon and other UXP derivative will be using it to fix a lot of broken sites, I thought this might be of interest to you.

So the problem is that virustotal.com does not load anymore see on [palemoon forums](https://forum.palemoon.org/viewtopic.php?f=70&t=28296&sid=1a74ab9807a15e011408239c58c671ca) and here is a fix that also works for palemoon https://github.com/Feodor2/Mypal68/issues/78.

The fix is to set `dom.moduleScripts.enabled` fo `false` in this case virustotal works with the full-feature modern interface.

This setting change could also fix or break other sites so it is not an option to let it disabled and forget about it just for a couple of websites.
It should not be hard to add to the list of rules a way to change this setting in the context of given sites. So I thought it could be added to palefill. A plugin was also written by a palemoon forum member but I cannot get it to run on other UXP based platforms such as SeaMonkey or BNavigator, even after changing the install.rdf file.

**Comment by martok** [comment]
For once, I'm on the other side of Maslows Hammer :)
Polyfill was straightforward, what disabling modules in the browser does is trigger their legacy scripts to load (impressive they have those!) - which we can also do directly with a bit of content magic.

**Comment by RamonUnch** [comment]
Amazing, thanks a lot, this was very fast!

PS: Did you consider also including IceApe-UXP and/or BNavigator (https://github.com/JustOff/github-wc-polyfill/issues/57) support, I can tell from using your add-on daily that it works fine with those browsers. I also asked this for the github-wc-polyfill addon but it seems there are some issues with that. I can manually edit the install.rdf file myself it is not a big deal though.

**Comment by martok** [comment]
Interesting question. I've been thinking about this for a day now, and I think I have found a solution. Separated to #20 for history visibility.
