### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by SeaHOH** [martok/palefill#2]
Plz keep the infos of copyright together with your referred codes.
https://github.com/martok/palefill/blob/56fdb09e5e7db8f7cf9895e730212fbd6ed23424/lib/polyfills.js#L175

**Comment by SeaHOH** [comment]
And the two are not the parts of attachShadow.

https://github.com/martok/palefill/blob/56fdb09e5e7db8f7cf9895e730212fbd6ed23424/lib/polyfills.js#L178
This origin is https://github.com/foobarhq/get-root-node-polyfill

https://github.com/martok/palefill/blob/56fdb09e5e7db8f7cf9895e730212fbd6ed23424/lib/polyfills.js#L199-L204

**Comment by martok** [comment]
Right, I need to take more care (especially now that people other than me use this :wink: ).

Should I credit you for the ShadowRoot and attachShadow polyfill, or is it based on something?

And yes, the "Load Diff" css fix was not supposed to stay there, I wanted to move that to a separate code block and forgot...

**Comment by martok** [comment]
> btw i currently hacked this plugin by replacing all occurences of github with some fantasy string, so it doesn't interfere with github-wc-polyfill. it might be advantageous for other users too to have a single knob to turn the duplicated functionality on or off.

This is something I've been avoiding for a while (even though this was the whole point of the rule engine design), seems I need face it. Tracking as #3...

**Comment by SeaHOH** [comment]
> Should I credit you for the ShadowRoot and attachShadow polyfill, or is it based on something?

The idea comes from @misteuk https://github.com/JustOff/github-wc-polyfill/pull/48 , and I expand it.
Just do the same to e.g. copyright of **Custom Elements** you put in the front of polyfills.js, you can find it in the front of bootstrap.js.

**Comment by martok** [comment]
Ok. I've pushed 7ecf7c83e, can you please have a look at it and let me know if everything is in the proper form? I don't want to misrepresent anything.
