### ISSUE TITLE
Not working with git.alchemyviewer.org

### ISSUE THREAD

**Issue by Elias011980** [martok/palefill#21]
Greetings,

Sadly, and unlike github-wc-polyfill, your exptension does not work for git.alchemyviewer.org: commits display a blank page. E.g.:
https://git.alchemyviewer.org/alchemy/alchemy-next/-/commit/05aea239de6bb74cb1e44a966ae8ec9f47f9be54

**Comment by martok** [comment]
Interesting, seems I missed a cherry-pick a fix somewhere since gwcp has not updated in a while... should be easy to find.

PM 31.1.0 was just available for a few seconds and then pulled, next release here will likely be soon™️ after.

**Comment by martok** [comment]
This is wild. Stupid copy&paste error in the "custom gitlabs" support, meaning no Gitlab script anywhere got fixes.
How did I not notice that in testing? No idea.

Sorry about that.
