### ISSUE TITLE
Microsoft Docs and Apple Developer

### ISSUE THREAD

**Issue by UCyborg** [martok/palefill#27]
Hello, I just want to bring these two sites to attention:

- [docs.microsoft.com](https://docs.microsoft.com/)
- [developer.apple.com](https://developer.apple.com/)

They both use Custom Elements. No other apparent specialties with Apple's site, but Microsoft's site is only recently easily fixable with the extension since one or two of the newly supported operators in Pale Moon are used numerous times in their code, so would be more difficult to fix for browsers that don't support optional-chaining and nullish-coalescing operators. I attempted changing usage of those operators a while back, but got lost and lost patience.

Additionally, it has a script which determines whether to show browser unsupported warning and unhides the relevant element on the page, check the debugger and look for the JS file with "deprecation" in the name. It seems to check for some features that aren't used yet, though theoretically some things could get triggered for logged in users. May be blocked with content blocking extension like uBlock Origin.

I suppose "std-customElements" rule can still be included for PM users and other browsers at this level of JavaScript support since it brings back functional index on certain pages such as [this one](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-createwindowexa).

**Comment by martok** [comment]
Oh hey, MSDN isn't one of these white desert design pages, there's actually content there? :sweat_smile: 

Thank you for pointing this out, implemented as suggested.

**Comment by Vangelis66** [comment]
> Additionally, it has a script which determines whether to show **browser unsupported warning** and unhides the relevant element on the page, ... May be blocked with **content blocking extension like uBlock Origin**.

I had it already blocked long time ago in **uBO** (legacy) with: 
```css
! https://docs.microsoft.com
docs.microsoft.com###unsupported-browser
docs.microsoft.com##.nav-bar:nth-of-type(1)
docs.microsoft.com##.is-hidden-mobile.border-top.nav-bar
```
😄
