### ISSUE TITLE
performance.mark function

### ISSUE THREAD

**Issue by biopsin** [martok/palefill#28]
![22-06-27--1656333906_scrot](https://user-images.githubusercontent.com/60029989/175945178-3a038982-d42e-4a46-b542-84b322b36de3.png)

Just started to happen even after updating plug to 1.14, I must hit F5 to update the page.

Pale Moon 31.1.0 - linux5.4

**Comment by Vangelis66** [comment]
Relevant upstream issue: 

https://github.com/JustOff/github-wc-polyfill/issues/68

Blocking `manuelpuyol` scripts is a workaround for me 😉 ... YMMV...

**Comment by biopsin** [comment]
Seems to be resolved, can I close this?

**Comment by martok** [comment]
Isn't resolved for me.

Also it *should* work, as far as I can see. The Performance global exists and has methods on its prototype, but they can't be called for some reason. Investigating...

**Comment by biopsin** [comment]
I spoke to soon, thing is if I enable webcomponents in Pale Moon (for finn.no), I dont experience the issue on github. But as webcomponents is incomplete its also disabled by default, so Im in a limbo state at this time.

**Comment by martok** [comment]
Are you currently seeing the performance.mark errors as in this report, or "parent is null"? If the latter, then that's #30 ...

**Comment by biopsin** [comment]
Yes, I see it in this report. I also see the performance.mark errors while enabling webcomponents in about:config, but I dont need to refresh the page like when disabled.

**Comment by martok** [comment]
There is clearly something weird going on, but I don't see any errors or warnings anywhere...

Can you retest with 1.15 and let me know how it goes? There might be some A/B testing going on that has me on a different feature flag...

This might actually be related to #30 - maybe some events just get misdirected. I currently have no idea how to properly fix it because I don't understand what is broken in the first place.

**Comment by biopsin** [comment]
I loaded up a fresh profile and the performance.mark errors are gone, so the issue is local. 
However v.1.15 resolves the extra reload one have to perform so Im closing this.
Thank you for you time!

**Comment by martok** [comment]
> I loaded up a fresh profile and the performance.mark errors are gone, so the issue is local.

Sounds like some A/B testing... maybe clearing local data for github on your main profile helps?

**Comment by biopsin** [comment]
@martok I also suspect there are some config settings that interfere here, but Im unable to pinpoint which at present time. A fresh userprofile seems to also have mitigated some other sitebugs I noticed on the old profile.
