### ISSUE TITLE
Configuration Options

### ISSUE THREAD

**Issue by martok** [martok/palefill#3]
The addon should have interactive options, for example en/disabling some fixes.

Maybe use a config file like ABL/uBlock instead of the object definition block?

Need to research how this works with bootstrap addons.

**Comment by martok** [comment]
Partially done in [1.6](/martok/palefill/releases/tag/v1.6), at least as exclusion lists.
I'm not convinced editable positive lists are all too useful for this addon - basically any new rule so far required some support code for the fix implementation anyway, which means a core update.

Keeping this open because I'd only really consider it done once #6 is implemented.

**Comment by martok** [comment]
The last two releases have seen actual action in the options screen and the dust has settled, so I'm closing this as done.

**Comment by rofl0r** [comment]
i've tried to use this feature lately (basically to use this together with gh-wc-poly), but i couldnt figure out the exact syntax. i guess it would help to have some examples there ?

**Comment by martok** [comment]
Which part of the examples in the manual is unclear?
