### ISSUE TITLE
DeepL doesn't work again

### ISSUE THREAD

**Issue by artenax** [martok/palefill#33]
An [optional chain](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) is required now. Can you fix it?

**Comment by martok** [comment]
Hi, sorry about the delay.

> Actually DeepL works in Pale Moon 31, but does not work in <=29. However, there are a lot of users of older versions. Honestly, I don't know how your extension can separate them.

There are probably ways, but I *don't want it to*. I target the current released version of Pale Moon, everything else is incidental or comes from contributors. This line was previously a bit unclear, the new website I just pushed makes that obvious.
