### ISSUE TITLE
`import` keyword polyfill?

### ISSUE THREAD

**Issue by roytam1** [martok/palefill#34]
It seems that more and more websites started using `import` keyword in their javascript frameworks.
I wonder if palefill will support this?

**Comment by martok** [comment]
ES6 modules (the `import` _keyword_) have been supported for ages and work as expected.

Dynamic module imports (the `import()` _function_) are not something that is possible in a polyfill, this needs to be implemented in the JS engine. See [UXP issue #1691](https://repo.palemoon.org/MoonchildProductions/UXP/issues/1691) for details.
