### ISSUE TITLE
ING-DiBa: cannot enter "DiBa key" when logging in

### ISSUE THREAD

**Issue by Gordon-Dry** [martok/palefill#38]
https://banking.ing-diba.de/OnlineBanking/index.html
The second step while logging in does not work.

The input fields for the chosen digits are not accessible, cannot enter anything.
![grafik](https://user-images.githubusercontent.com/29145213/180467506-ee9b7397-c4f0-4cf0-a7c5-1d14999e5d23.png)

**Comment by martok** [comment]
Ask yourself: do you really want one random guy's addon to have access to your bank account, possibly also weakening their security measures against other things along the way?
Doesn't really matter what you answer, banking sites are one thing I'm not going to touch.

(This might just be a case of adding customElements, at least that's the first error message. But yeah. Nope.)
