### ISSUE TITLE
Header elements in the top-left corner on VirusTotal

### ISSUE THREAD

**Issue by AstroSkipper** [martok/palefill#39]
The header elements in the top-left corner are a bit broken on the website **VirusTotal.com**. Some elements are overlaid and difficult to reach or read, like for example, **Sign-in** or **Sign-out**. Tested in **New Moon 28.10.6a1**, latest build from **2022-07-15** and **Serpent v52.9.0 (2022-07-15)**, both **32-bit** with **palefill 1.17** installed. OS is Windows XP Professional.

Kindest regards, AstroSkipper [![panne-ordi-2.gif](https://i.postimg.cc/t44WXfqp/panne-ordi-2.gif)](https://postimg.cc/TpBp0t54)

**Comment by Vangelis66** [comment]
This is how 
https://www.virustotal.com/gui/home/upload
is being rendered in a **Chromium-86** fork: 

![ch86-vt](https://user-images.githubusercontent.com/9669492/180878567-108f860c-a199-43dd-be23-5b010232d8f7.JPG)

OTOH, on a **UXP-based** browser with latest **palefill**, it renders as below: 

![UPX-VT](https://user-images.githubusercontent.com/9669492/180878745-164e99c5-a9c2-43b6-9c12-50d986595028.JPG)

i.e. the four "buttons" at the far right of the header (in Chromium) are being superimposed on the four "buttons/links" at the far left of the header... 😞 
Obviously, **VT are using Chromium-specific CSS syntax that UXP can't cope with** (yet?) ... Additionally, when the page is being scrolled down, the four links on the far left remain as sticky/static, while the four buttons of interest (including the `Sign in` one) are moving out of sight: 

![UPX-VT2](https://user-images.githubusercontent.com/9669492/180879714-c3169858-6083-49b1-b484-9dd6d3f017d2.JPG)

I have no code solution per se for this predicament, but if you're not that interested in the four "Enterprise" links on the far left (i.e. **Intelligence**, **Hunting**, **Graph**, **API**), you can move them out of sight via a **uBlock Origin** cosmetic filter: 
```css
www.virustotal.com###enterprise-features
```
leaving the four other buttons uncluttered: 

![UPX-VT3](https://user-images.githubusercontent.com/9669492/180881207-364c0c09-bb89-47a8-969b-8f68ef061c6e.JPG)

Again, the far left button ("Solutions") is unusable (its popup opens out of view) ,,,

**Comment by martok** [comment]
> Obviously, **VT are using Chromium-specific CSS syntax that UXP can't cope with** (yet?) ...

Nothing about Chromium, just the "we will never implement Web Components" stance from several years ago coming back to bite UXP. Thankfully that has changed, but there's still some catching up to.

ShadowDOM's `::host` selectors are implemented as of [#1593 on RPMO](https://repo.palemoon.org/MoonchildProductions/UXP/issues/1593), but still behind the `dom.webcomponents.enabled` gate along with everything else.
Not much to do about it from this end...

**Comment by Vangelis66** [comment]
Thanks for your elaboration on this! 👍 😄 

As I see it myself, my quoted reference in your comment above isn't far from the truth after all :wink: ; Chrome(/-ium) has full support for **Web Components** (and **ShadowDOM**'s `:host` selectors) since a long time ago, so the **VT** page code is sure to work as planned in **Chromium** (and forks of, and in **Firefox**), but not **UXP**, currently...

**Comment by martok** [comment]
Looks like VT now builds their app with ShadyCSS for the fallback scripts. Nothing else to do here then.
