### ISSUE TITLE
unusual csp on github?

### ISSUE THREAD

**Issue by AroKol78** [martok/palefill#40]
Serpent52 (2022-07-15)
`Couldn’t parse invalid host .actions.githubusercontent.com`
`Couldn’t parse invalid host .githubusercontent.com`

(by the way, is it possible to exclude third parties?, e.g. `unpkg` on `github`)

**Comment by martok** [comment]
That old friend again:
![xkcd](https://imgs.xkcd.com/comics/perl_problems.png)


> (by the way, is it possible to exclude third parties?, e.g. `unpkg` on `github`)

You can really tell when I just stopped caring...
