### ISSUE TITLE
Consider hosting the xpi package in a site that doesn't require WebComponents

### ISSUE THREAD

**Issue by jobbautista9** [martok/palefill#47]
Originally reported in Pale Moon forum [topic 28849](https://forum.palemoon.org/viewtopic.php?f=70&t=28849)

Currently it's not possible to install the extension with a fresh profile of Pale Moon; seems like GitHub has broken the loading of list of assets in the releases page. See screenshot below.

![Screenshot_2022-09-21_13-17-35](https://user-images.githubusercontent.com/73383951/191420444-0c740356-eb14-47fc-a2f3-ea13169b9657.png)

This leads to a chicken-and-egg problem. The solution to that problem is to install Palefill, but it's impossible to install Palefill when GitHub is broken for the user.

Possible solutions include letting the Pale Moon add-ons site host the xpi, mirroring the git repo and releases to repo.palemoon.org, or if you really don't want to use Pale Moon infrastructure, host the repo in Codeberg.

**Comment by jobbautista9** [comment]
Ah, it's possible to use the direct link to the xpi, but that requires help from another user who already has the extension installed. So yeah, still not ideal...

**Comment by martok** [comment]
Hm, true.

Until they somehow manage to break a static site linking a static file, there is now a direct link on the main landing page (the one APO links to as well). Needs to be manually updated on each release, but that should be doable ;-)
![image](https://user-images.githubusercontent.com/109197/191446335-42b73455-26a2-4997-aedd-d295bdc3fd63.png)

**Comment by jobbautista9** [comment]
Nice, thanks! I also realized that @FranklinDM's Project Fresco provides an up-to-date direct link to the xpi too at https://projectfresco.github.io/addons/get?addon=palefill, maybe you want to point there instead so that you don't have to update the Install link every release. :)

**Comment by Vangelis66** [comment]
... This is only a kludge, but still a viable workaround for **fresh profiles** of **UXP-based** browsers:

If one wishes to install the latest release version of `palefill`, it's hosted (by GitHub) in: 

https://github.com/martok/palefill/releases/latest

At the time of writing, this autodirects to: 

https://github.com/martok/palefill/releases/tag/v1.21

but, as explained, `Assets` are behind **CustomElements** and, thus, inaccessible 😞 ...

Re-formulating the above URI to include the `expanded_assets` subpath like below: 

https://github.com/martok/palefill/releases/expanded_assets/v1.21

will provide a **minimal installation page** where the XPI link is **accessible to fresh profiles of UXP-derived** browsers!

![EA](https://user-images.githubusercontent.com/9669492/192121598-21a35b77-c12d-4b7d-9d9c-409f1b989493.JPG)

I bet someone with the appropriate skills could write a GM **userscript** and/or a "legacy" **extension** to auto-perform the URI-manipulations described above... 😉
