### ISSUE TITLE
Github: optional chaining (again)

### ISSUE THREAD

**Issue by martok** [martok/palefill#5]
Github uses more optional chaining now:

```
19:19:11.200 SyntaxError: expected expression, got '?'[Learn More]  
8933-d8b0634d2391.js:49:2049
19:19:11.393 SyntaxError: expected expression, got '.'[Learn More]  
2403-3e07b8533bbd.js:1:7833
19:19:11.397 SyntaxError: expected expression, got '?'[Learn More]  
7253-67d624cbaf0c.js:1:10803
```

This currently breaks (at least) the editor preview tab.

**Comment by martok** [comment]
This did not get all of them, also some integrity overrides are missing.

**Comment by martok** [comment]
There are still some things that throw errors at runtime, but things seem to work... try [1.6b1](https://github.com/martok/palefill/releases/tag/v1.6-beta.1) if you need a function that 1.5 missed (quite a few...).

I'm not very happy with the way it's resolved now, but hey... can't always get what you want.

**Comment by Vangelis66** [comment]
FYI: https://github.com/JustOff/github-wc-polyfill/issues/58#issuecomment-1065789405

😄

**Comment by martok** [comment]
Oh bloody hell :rofl: 

At least we learned what to do when it happens for real :roll_eyes:

**Comment by dirkf** [comment]
That seems to have happened now.
