### ISSUE TITLE
docs.microsoft.com has become learn.microsoft.com

### ISSUE THREAD

**Issue by UCyborg** [martok/palefill#52]
When you find a moment, the relevant rule needs updating as any link to [docs.microsoft.com](https://docs.microsoft.com/) now goes to [learn.microsoft.com](https://learn.microsoft.com/).

**Comment by Vangelis66** [comment]
Relevant previous (fixed) issue: #27 ;
relevant previous fix commit: 01beec444cd3d866b2db2348742f931a8872cbc9 ; 
additionally, MS do feature detection and then generate `unsupported browser` header in UXP, so if the extension could take care of that, too, it'd be advantageous 😉 (related discussion [here](https://msfn.org/board/topic/182647-my-browser-builds-part-3/page/198/#comment-1227302)) ...

**Comment by Vangelis66** [comment]
> additionally, MS do **feature detection** and then generate `unsupported browser` header in **UXP**, so **if the extension could take care of that, too, it'd be advantageous** 😉 

Many thanks for implementing that! 👍 ...

(The `unsupported browser` banner is now gone in `palefill-1.23` 🎉 ; to also remove the top "promo" header by **MS**, I'm using the below cosmetic filter in `uBO-legacy`: 
```css
learn.microsoft.com###banner-holder
```
😃 )
