### ISSUE TITLE
GitHub Actions: "Show more" buttons unresponsive...

### ISSUE THREAD

**Issue by Vangelis66** [martok/palefill#54]
Browser: **Serpent** v52.9.0 (2022-08-24) (32-bit)
Extension version: `palefill-1.23` (latest stable release)

STR

Visit/load: https://github.com/ytdl-patched/yt-dlp/actions/runs/3258194065

Under **Annotations**, you'll notice 14 warnings, **12** of which have a "**Show more**" button: 

![GHA-SM1](https://user-images.githubusercontent.com/9669492/196066923-bcf71707-4cd1-417a-8773-2031a7ebda44.JPG)

Current behaviour: 

Clicking any of those (12) "**Show more**" buttons will have **no effect at all** 😢 ...

Expected behaviour: 

In a **Chromium**-based browser, clicking a "**Show more**" button will **reveal additional text** (and a "Show less" button will also display): 

UXP: 
![GHA-SM2](https://user-images.githubusercontent.com/9669492/196066894-2cf4e224-9c17-418e-b949-62e81768b6b5.JPG)

Chromium 86: 
![GHA-SM3](https://user-images.githubusercontent.com/9669492/196067020-45f84285-8018-47e3-937f-1531757714a9.JPG)

Nothing I can spot is printed in Web Console... 😭

**Comment by jrfnl** [comment]
I can confirm, I have observed the same behaviour. Same thing is still happening with Palefill 1.24 on PaleMoon 31.4.1.win64.

**Comment by jrfnl** [comment]
Thank you @martok for working on this! I look forward to testing it.

**Comment by Vangelis66** [comment]
I can confirm latest code snapshot 
`palefill-v1.24-6-git-20221203-gcf19123`
has fixed this! 🎉 

Congrats! 🥇
