### ISSUE TITLE
drive.google.com scroll bar

### ISSUE THREAD

**Issue by snottyone** [martok/palefill#56]
on google drive, i have a working scrollbar in the folder window at left, but not in the files window (in list and tile view). maybe that is fixable?

and:
i only just found this, via r/Palemoon, and i'm already SO happy about fixed reddit, leo, and not the least the github assets dropdowns. thank you very very much.

**Comment by martok** [comment]
This can be fixed with user CSS which is (as stated multiple times before) out of scope for this addon.

The fact that a new user doesn't know that makes it obviously a doc issue.

**Comment by martok** [comment]
More specifically, you'll want [this bit](https://martok.github.io/palefill/styles.html#drivegooglecom) in Stylem/Stylish/userContent.css
