### ISSUE TITLE
Support for Fanbox website

### ISSUE THREAD

**Issue by hujan86** [martok/palefill#57]
Since support for Pixiv was added, I was wondering if you could extend it to the Pixiv-related site: "https://www.fanbox.cc/".

Currently Pale Moon displays a blank white page when accessing the site.

According to the Error Console:
> Timestamp: 10/31/2022 9:17:00 PM
> Error: TypeError: window.customElements is undefined
> Source File: https://s.pximg.net/www/js/fanbox/fanbox.9e051f915d9b1173277d.js
> Line: 195

**Comment by Vangelis66** [comment]
In extension's file `./lib/builtin-rules.js`, navigate to **L68** and just add (as L69): 
```diff
 ! --
 www.pixiv.net
 accounts.pixiv.net
+*.fanbox.cc
     std-customElements
 ! --
```
`*.fanbox.cc` should cover both the main site ("Home"), as well as the "Announcements" sub-site (https://official-en.fanbox.cc/posts); alternatively, you could add two standalone lines: 
```diff
 ! --
 www.pixiv.net
 accounts.pixiv.net
+www.fanbox.cc
+official-en.fanbox.cc
     std-customElements
 ! --
```
Not a user myself of either `pixiv.net` nor `fanbox.cc`, so can't tell whether other aspects of the site demand more than  `std-customElements` 😉 ...
