### ISSUE TITLE
[Regression]GitHub: Hovering over "linkified" issues/PRs/commits doesn't generate useful popup anymore... 

### ISSUE THREAD

**Issue by Vangelis66** [martok/palefill#65]
Extension version: `palefill-v1.24`

**Description**

I was elated that the new update fixed #60 (:+1: ), but soon my joy was somewhat dimmed :disappointed:, because I stumbled upon a new regression (adding to #64) on **a GitHub feature I extensively use**...

**STR**

1. Navigate to: https://github.com/martok/palefill/commit/2a9bc643aa9008ef3a5ec02431bd60ea38a2cf12
2. Inside the commit's description, **put the cursor onto** `#60` (or `#30`; these are issues [hopefully] resolved by the commit).

Expected behaviour: 

A **popup window is being displayed**, with details about the **issue** (or **PR**, if the hovered "number" corresponds to a **PR**): 

![PFbug1](https://user-images.githubusercontent.com/9669492/205200444-60049bcb-e380-48f1-b245-a4d8dc6ecf15.PNG)

Above screengrab is with a Chromium **86** fork (similar result with `palefill-1.23`, minus the relative timestamp) 

Actual behaviour: 

**No popup window is being displayed** - I have to middle-click on `#60` and open the linked issue in another tab, to see what it's about :disappointed: ...

With a commit: 
1. Navigate to [#64](https://github.com/martok/palefill/issues/64)
2. Hover over linkified commit hash `2a9bc64`

Expected behaviour: 

A **popup window is being displayed**, with details about that commit: 

![PFbug2](https://user-images.githubusercontent.com/9669492/205202371-8989750a-4ef8-4b8c-9409-6168f5ebefd6.PNG)

Above screengrab from Chromium **86** fork (similar result with `palefill-1.23`, minus the relative timestamp). 

Actual behaviour: 

**No popup window is being displayed** - I have to middle-click on `2a9bc64` and open the linked commit in another tab, to see what it's about :disappointed: ...

Hopefully I'm not coming across as ungrateful and/or entitled :wink: , I'm not a coder but (I think) I've formed a good idea of how much **time-consuming** all those "fixes" must be, as a result the **maintainer**'s (and other **contributors**') efforts are indeed highly appreciated by me :heart: ...

For #64, a "workaround" was cited, hopefully something will come up for this issue, too... :smiley_cat: 

**Addition**: As spotted later by @jrfnl : 

> the mouse-overs when hovering over a contributor's name **don't show anymore**.

**Comment by Vangelis66** [comment]
`GitHub docs` entry for the "links" manifesting this regression in `palefill-1.24`: 

https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls

(I wasn't aware of the **exact terminology** when I opened this issue, luckily I was close to it 😜 ...)

**Comment by jrfnl** [comment]
Came here to report the exact same thing. Also noticed the mouse-overs when hovering over a contributor's name don't show anymore.

Using PaleMoon 31.4.1-win64.

In the console, the following message shows on page load, but may very well not be related:
```
Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively. 1 (unknown)
```

**Comment by martok** [comment]
> ```
> Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively. 1 (unknown)
> ```

It's not related, that's been there forever. [Looks like it was un-deprecated](https://w3c.github.io/webappsec-csp/#directive-child-src) and UXP doesn't know that.
"Living standards", yay.

**Comment by jrfnl** [comment]
Thank you @martok for working on this! I look forward to testing it.

**Comment by nicolaasjan** [comment]
Thanks!
https://github.com/martok/palefill/commit/395dbc64f5aa02d4f4524ce7eddb624536ec94d7 fixed this.

**Comment by Vangelis66** [comment]
I can confirm 🎉 !

It probably serves nothing now 😉 , but yesterday night I did some `git-bisection` with regards to this issue and found out that: 

code snapshot `palefill-v1.23-3-git-20221107-g2e6e6f8` is the "last GOOD", while 
immediately next code snapshot `palefill-v1.23-4-git-20221201-g677dfa9` is the "first BAD" 😞 ; 

thus, 677dfa9 was responsible for the regression (and not `DarkTree` per se); which coincides with 395dbc6 as being the fix (the former removed GH polyfill `github-compat-838cedbb.js`, while the latter re-introduced some "needed" parts of it) ...

Much appreciated **martok** ! 😄
