### ISSUE TITLE
github again

### ISSUE THREAD

**Issue by AroKol78** [martok/palefill#69]
Serpent52 (20221216034925) + palefill1.25
links in `Source File:`
```
Error: TypeError: 'querySelectorAll' called on an object that does not implement interface Element.
Source File: https://github.com/martok/palefill
Line: 11
```
and 
```
Error: TypeError: 'querySelectorAll' called on an object that does not implement interface Element.
Source File: https://github.com/martok?tab=repositories
Line: 6
Error: ReferenceError: Turbo is not defined
Source File: https://github.com/martok?tab=repositories
Line: 16
```
and
`https://github.com/`
```
Error: RangeError: invalid value unit for option style
Source File: https://github.githubassets.com/assets/vendors-node_modules_primer_view-components_app_components_primer_primer_js-node_modules_gith-3af896-288086fb1606.js
Line: 203
```

**Comment by Vangelis66** [comment]
The first two reported **Errors** somehow are linked to the use of the new [js-darktree](https://github.com/martok/js-darktree) ShadowDOM replacement polyfill...

STR: 

1. Install `palefill-v1.23-4-git-20221201-g677dfa9` code snapshot; that's the last with the **old** ShadowDOM polyfill; load: 
https://github.com/martok?tab=repositories
result: 
**ALL** those errors are gone!
2. Install `palefill-v1.24`, the first where **js-darktree** is being used; load: 
https://github.com/martok?tab=repositories
result: 
```js
TypeError: 'querySelectorAll' called on an object that does not implement interface Element.
```
errors start appearing 😢 ... The **second** error for above URI, 
```js
Error: ReferenceError: Turbo is not defined
Source File: https://github.com/martok?tab=repositories
Line: 16
```
isn't generated, too, until `palefill-v1.24-3-git-20221203-g395dbc6` code snapshot is installed...
"Turbo" = **Soft Navigation** and, as I've detailed [here](https://github.com/martok/palefill/issues/53#issuecomment-1336248530), that specific `palefill` code snapshot is **the one that permanently breaks GitHub Soft Navigation** 😞 ...

I have no clue about the last 
```js
Error: RangeError: invalid value unit for option style
```
error, probably a **UXP**-CSS-related deficiency 😞 ...

**Comment by SeaHOH** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1638298

A bug of the option`style` for `Intl.NumberFormat` and `Number.prototype.toLocaleString`, style `unit` has being unsupported.

**Comment by Vangelis66** [comment]
> The first two reported Errors somehow are linked to the use 
> of the new [js-darktree](https://github.com/martok/js-darktree) ShadowDOM replacement polyfill...

```js
Error: TypeError: 'querySelectorAll' called on an object that does not implement interface Element.
```
and 
```js
Error: ReferenceError: Turbo is not defined
```
**not present anymore** when loading
https://github.com/martok?tab=repositories
with `palefill-v1.25-4-git-20221228-g9674444` code snapshot installed... 
(**js-darktree** fixed via [3af3847](https://github.com/martok/js-darktree/commit/3af38477bf98a9112682ee399860abd81ed178df))

Many thanks, have a Happy New Year! 🎅

**Comment by AroKol78** [comment]
Serpent52 (20230106125713) + palefill1.25 (+ https://github.com/martok/palefill/commit/28fceda6b56d4f614b908270bba290f5336bac3c + https://github.com/martok/palefill/commit/734c7988fe0e4daf174b15ed8c155baef2e089f2 + https://github.com/martok/palefill/commit/9674444afde74724c11242b22ec9e9a404395597)

navigation on github is terribly slow especially if you want to see the files
(i navigate faster on yt and I don't have such problems - strange, to see a few lines of text requires a lot of computing power)
example `https://github.com/Feodor2/Mypal68/blob/main/modules/libpref/init/all.js`
![bardzowolno001](https://user-images.githubusercontent.com/70756447/211152284-6bf5516e-c757-4659-b48b-b1ceccb096a0.JPG)

p.s.
thank you for your contribution and work on browser development :1st_place_medal:

**Comment by Vangelis66** [comment]
> example 
> https://github.com/Feodor2/Mypal68/blob/main/modules/libpref/init/all.js

I can easily replicate on my **old** laptop, with a 2007-era `Intel Core 2 Duo CPU T5250 @1.50GHz` ("Merom") CPU... Clicking `Continue` once (sometimes, it appears for a second time 😞 ...) **eventually** makes the page load fully...

How old/powerful is your CPU?

> strange, to see **a few lines of text** require a lot of computing power)

This isn't **just text** and, certainly, not a "few" lines only 😉 ... The file viewed consists of 6,069 lines of code... If you want the "text-only" version of that file, then use (s/blob/raw/g): 

https://github.com/Feodor2/Mypal68/raw/main/modules/libpref/init/all.js

(loads in 1s here...).

I suppose the migration to `js-darktree` made things somewhat "slower" in this context... Not much can be done, probably...

**Comment by AroKol78** [comment]
> How old/powerful is your CPU?

Intel Core 2 Duo 2.33GHz
on the old phone with worse parameters and with the new FF- no problem

> This isn't **just text**

for me it's just text, not quantum physics

it's just funny

**Comment by Vangelis66** [comment]
> on the old phone with worse parameters and with the new FF- no problem

... Apples and oranges 😉 ... 
1. "**Old phone**" not using **Windows XP SP3 32-bit** (a desktop targeting OS)
2. "**New FF**" (employing **electrolysis** by default) supports current GitHub **natively**, doesn't require `palefill` to load it (in a **single** process, too) ... 

Either **martok** is able to further fine-tune the `palefill`-included polyfills or not... 

One thing is sure: MS will continue making GitHub more bloated and resource-hungry as time goes by 😠 ; they, practically, only test it on **latest Edge** snapshot, on Win**10**/**11**, on **2020+** H/W (which they can easily afford) ...

**Comment by Vangelis66** [comment]
Another (**"tall"** 😉 ) **GitHub page** where the "**Unresponsive script**" issue can be easily observed (notably on **old H/W**): 

https://github.com/yt-dlp/yt-dlp/commit/bfd973ece3369c593b5e82a88cc16de80088a73e

**Comment by AroKol78** [comment]
> Another (**"tall"** 😉 ) **GitHub page** where the "**Unresponsive script**" issue can be easily observed (notably on **old H/W**):
> 
> [yt-dlp/yt-dlp@bfd973e](https://github.com/yt-dlp/yt-dlp/commit/bfd973ece3369c593b5e82a88cc16de80088a73e)

i tried a couple of times = Intel Core 2 Duo 2.33GHz is enough not to notice the message
it doesn't change the fact that it's generally slow on github

**Comment by Vangelis66** [comment]
> is enough **not to notice** the message

... Try also scrolling down the page (e.g. with [middle] mouse wheel) before it loads fully...
FWIW, the warning can be suppressed by setting a higher (to default `20`) value to pref `dom.max_script_run_time` ; this **doesn't make GitHub load any faster**, just gets the warning out of sight :wink: ...

**Comment by NintendoManiac64** [comment]
I'm slightly late to this thread but, protip from a hardware person - the Core 2 Duo is compatible with RMClock which can be used to underclock the CPU even on a laptop to slower speeds.  There was a signed version compatible with Win7 64bit but it was posted onto a forum that has since been closed... though I *do* still have a copy so maybe I should upload it to archive.org or something.

For Nehalem and newer Intel CPU, the same thing can basically be achieved with ThrottleStop.

For AMD CPUs, you can use CrystalCPUID for K8-based CPUs, K10stat for K10/K10.5 CPUs, and BrazosTweaker for Bobcat CPUs, and Ryzen Master for anything Zen-based.  AFAIK, there was never any OS-side underclock utility made for both Jaguar as well as the Bulldozer-derived cores (Piledriver, Steamroller, Excavator).

**Comment by AroKol78** [comment]
```
Error: TypeError: navigator.clipboard is undefined
Source File: https://github.githubassets.com/assets/vendors-node_modules_stacktrace-parser_dist_stack-trace-parser_esm_js-node_modules_github_bro-327bbf-0aaeb22dd2a5.js
Line: 1
```

**Comment by Vangelis66** [comment]
> `Error: TypeError: navigator.clipboard is undefined`

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/clipboard

... first implemented in Fx **63**, released 2018-10-23; but does it cause here any real **functional breakage** aside from that console entry?
