### ISSUE TITLE
imgur albums

### ISSUE THREAD

**Issue by rofl0r** [martok/palefill#7]
example: https://imgur.com/a/VofNBkK

there's a spinning wheel, and nothing happens. console says some stuff about "USP".

**Comment by martok** [comment]
Works for me. Spinner for a fraction of a second, then the image loads.

The errors and failed requests seem to be from adblocking the trackers, I get the exact same output in Edge with uBlock.

**Comment by rofl0r** [comment]
thanks. so i guess it's my fault for using adblockers.

**Comment by martok** [comment]
Hm? What I meant to say was, imgur works. Even with adblockers.
I still get the same log messages as you, they are from their trackers and mean nothing.
![image](https://user-images.githubusercontent.com/109197/158485017-3d2735b0-980b-4cc6-86c1-1e3897481f26.png)

Do you use additional privacy addons? NoScript loves to break random things, maybe something else is overly aggressive?

**Comment by rofl0r** [comment]
i'm using a custom blacklist for tinyproxy's domain filter, because filtering in C is much faster than filtering in JS...
