### ISSUE TITLE
How can I sponsor ?

### ISSUE THREAD

**Issue by jrfnl** [martok/palefill#71]
I use Palefill every day and wouldn't know what to do without it!

I'd love to be able to give back a little while I can, so how can I sponsor development of this project ?

**Comment by martok** [comment]
That must be the christmas spirit :laughing: 

However.
I'd consider it more useful to directly support the [Pale Moon project](http://www.palemoon.org/donations.shtml), which (apart from just keeping things running and providing services like Sync) pays developer bounties from donated funds. In other words: help the platform move towards a point where less and less Palefill is needed.

If you wish to specifically support me though: coincidentally I've made a Ko-fi account just a few days ago to support others. Assuming I've done everything correctly, It should be accepting tips now: [ko-fi.com/martok_dev](https://ko-fi.com/martok_dev).

**Comment by jrfnl** [comment]
> That must be the christmas spirit

@martok Well, for me, it actually has a very practical reason - I'm self-employed with highly fluctuating income year over year, so only at the end of the year can I gauge if and if so, what I can afford to spend in donations ;-)

> I'd consider it more useful to directly support the [Pale Moon project](http://www.palemoon.org/donations.shtml)

They were also on my list and already got a donation too ;-)

> Assuming I've done everything correctly, It should be accepting tips now

Looks like it does 👍🏻

**Comment by martok** [comment]
> @martok Well, for me, it actually has a very practical reason - I'm self-employed with highly fluctuating income year over year, so only at the end of the year can I gauge if and if so, what I can afford to spend in donations ;-)

Haha, that makes sense :+1: 

> They were also on my list and already got a donation too ;-)

Perfect!

> Looks like it does 👍🏻

Looks like it. Thank you! :tada: :heart: 

(The link now also lives on my profile overview readme thingy.)
