### ISSUE TITLE
Support for Nextcloud

### ISSUE THREAD

**Issue by Evhorizon** [martok/palefill#73]
Hi, I'm using the latest version of Basilisk and Nextcloud is barely showing a navigation bar, nothing else. I wonder if palefill could support this website in a future release. Thanks in advance.

**Comment by martok** [comment]
Yeah, I know... same for my Uni's Nextcloud.

Unless I've missed something in a quick test we won't need to do anything after the next platform release. @Vangelis66 any chance you're using a Nextcloud in the new Serpent?
 
In general it's also a bit of an architecture problem with self-hosted sites. Even the way we do Gitlabs currently is basically unmaintainable, so even if something more is needed, can't do much until #45 is resolved.

**Comment by Vangelis66** [comment]
> @Vangelis66 any chance you're using a **Nextcloud** in the **new Serpent**?

...Sadly, no 😞 ... However, "new" **Serpent 52.9.0** builds are publicly available for one to try 😉 : 
```
x86
https://o.rthost.win/basilisk/basilisk52-g4.8.win32-git-20221231-3219d2d-uxp-120ac6d55-xpmod.7z
x64
https://o.rthost.win/basilisk/basilisk52-g4.8.win64-git-20221231-3219d2d-uxp-120ac6d55-xpmod.7z
```
Require **Windows** XP SP3 32-bit (x86 build) or **Windows** XP SP2 64-bit (x64 build) and **higher** (Vista SP2, 7 SP1, etc.); **Linux** builds are not available, though...

**Comment by martok** [comment]
I was more asking for daily/deeper use, from spot-check in Pale Moon snapshots at least the main features work.

**Comment by martok** [comment]
Looks OK in PM 32.2.0
