### ISSUE TITLE
Question - Regarding Dynamic Module Import - based on existing Waterfox Classic patches

### ISSUE THREAD

**Issue by Sa-Ja-Di** [martok/palefill#75]
Hey, as i have found no other way to contact you - i simply open another issue for this quick question.

As you have also been able to bring over the Waterfox Classic entries for the Regex stuff into Pale Moon, what do you think are the chances this can also be done with 

Dynamic Module import
(https://repo.palemoon.org/MoonchildProductions/UXP/issues/1691)

Moonchild meant that the patches cant be "cherrypicked"

Waterfox classic Dynamic import Part 1
https://github.com/WaterfoxCo/Waterfox-Classic/pull/143

Waterfox classic Dynamic import Part2
https://github.com/WaterfoxCo/Waterfox-Classic/pull/144

but you have proven it can also be done with more complex stuff. So, what is your opinion regarding this matter?

Happy new year btw. :)

**Comment by martok** [comment]
Moonchild is totally right, that's not even close to cherry-pickable.

Tracking for myself on RPMO, but I don't currently see a good way forward, either...
