### ISSUE TITLE
Cannot view the self-hosted GitLab for Student Transfer

### ISSUE THREAD

**Issue by RinTohsaka64** [martok/palefill#77]
Simply put, Palefill seems to be unable to view the self-hosted GitLab that is used for Student Transfer (an amateur visual novel):

- https://git.student-transfer.com/st
- https://git.student-transfer.com/st/student-transfer

**Comment by martok** [comment]
Add it to the list of custom self-hosted Gitlab sites in settings, like this:
![image](https://user-images.githubusercontent.com/109197/211938819-91b8cfd0-1e81-45c4-b6f1-9884d2604288.png)
