### ISSUE TITLE
Support for arte.tv

### ISSUE THREAD

**Issue by Gordon-Dry** [martok/palefill#79]
The main rendering issue I see for a few weeks now is white text on white background *grin*

Please check https://www.arte.tv/en/

**Comment by Vangelis66** [comment]
> Please check https://www.arte.tv/en/

I'm running latest **Serpent 52.9.0** (2023-01-19) (32-bit)/UXP, latest `palefill-1.26` installed; `arte.tv` loads and renders fine here, even their embedded web player works as intended: 

https://www.arte.tv/en/videos/099238-046-A/the-gender-of-the-soul-episode-2/

![ARTE](https://user-images.githubusercontent.com/9669492/214601838-06ab134b-c2c8-43d8-8de2-33732a7de3cf.png)

FWIW, I have `browser.display.prefers_color_scheme` inside `about:config` set to `2`, so sites display their **dark** usestyles, whenever available...

**Comment by Vangelis66** [comment]
... Unfortunately, I can't launch official **PM32** in my current **OS** now (but chances are I'll have access to a `Win7 SP1 x64` laptop sometime tomorrow 😉 ); I even tried with a **new/fresh profile** of **Serpent 52** (it's a fork of the official [Basilisk/UXP](https://www.basilisk-browser.org/) browser) and at **default settings** I still get the dark iteration of `arte.tv` here: 

![ARTE2](https://user-images.githubusercontent.com/9669492/214715967-f7e0ae22-3b64-45c8-b413-a2e2350fe191.png)

Furthermore, the `arte.tv` site functions as expected even without `palefill` installed (fresh profile = **no extension** whatsoever added), so I doubt your predicament is actually `palefill` related (or could be mitigated by _it_) ... 

For the time being, I'll refrain from posting further, at least until I assess this better myself (hopefully tomorrow) or someone else (besides OP 😉 ), actually running **PM32**, can chime in sooner...

**Comment by Vangelis66** [comment]
... And, as promised :wink: : 

**OS**: Win7 SP1 64-bit
**Browser**: Pale Moon 32.0.0 (32-bit)
**Browser Profile**: Fresh new one, at 99.99% **default settings** (only the menu bar was made to display, plus tabs-on-top)

Loading https://www.arte.tv/en/videos/series/ => 

![PM32-1](https://user-images.githubusercontent.com/9669492/214996147-50828489-3400-4aa0-8c6a-9c0bae6b3a36.jpg)

... and **full-page screenshot** (via Web Developer Tools): 

![PM32-2](https://user-images.githubusercontent.com/9669492/214996527-2c7dc6a7-e9da-422d-b0e3-fc836f3b9e60.jpg)

@Gordon-Dry : The issue you posted about is most probably related to your 
1. browser profile (a setting/extension) ?
2. your OS (no info about it, BTW...) ? 
3. your H/W (GPU and/or GFX driver) ?

Try disabling graphics H/W acceleration, if enabled by default... Can't think of anything else myself ... Seems unlikely the author of **this extension** could help you fix it... 

Kind regards :smile:

**Comment by Gordon-Dry** [comment]
Well, every 2 or 3 years it's the same, people say "just start with a new profile" again and again.
Do you have a clue how much it sucks to start with a fresh profile and fiddle it to workability?
And no, I'm not that autistic guy who wants to stay on the same status quo for years, I'm able to adapt as soon as it's not a pseudo-standard or some circumstance made by wokists etc.
I lost beloved addons and the addon devs did not dare to support Pale Moon. But I can live with that as long as any dev dares to create an alternative within a tolerable time frame.

This is Windows 10 64-bit / GeForce GTX 1660 Super with latest driver 528.24 btw.

And yes, I'm aware of the fact that many web admins are not able to create W3C conform sites but Google- and Microsoft-pseudostandard-conform sites, so we users of Pale Moon et al have to suffer in this new normal of a globalized world full of incompetence and selfishness.

**Comment by Gordon-Dry** [comment]
I found a workaround.
[NoSquint](https://addons.palemoon.org/addon/nosquint/) got site specific override settings for background and text colors.
