### ISSUE TITLE
pixiv - "'・・・" menu next to the 'Follow' button is missing

### ISSUE THREAD

**Issue by NintendoManiac64** [martok/palefill#80]
When you're logged into to pixiv, next to the `Follow` button on a given artist's profile, there is a menu button that looks like `・・・`

Simply put, this menu is missing when using Palefill rather than having WebComponents enabled; if you have WebComponents enabled, then the `・・・` menu is present regardless of whether Palefill is installed or not.

Example artist page (anime cuteness warning): https://www.pixiv.net/users/4692512

**Comment by NintendoManiac64** [comment]
Look closer at the date this was created—`dom.webcomponents.enabled` was not enabled by default when this was created.

**Comment by martok** [comment]
I know, I'm just cleaning up old issues.

**Comment by NintendoManiac64** [comment]
Ah, alright. I was just thinking that the 8 in 18 could look like a 6 if you're not careful, and since today is Jan.16 (albeit 2024) it could make one think that this was submitted today.
