### ISSUE TITLE
Pale Moon 32 compatibility

### ISSUE THREAD

**Issue by jobbautista9** [martok/palefill#81]
Since you're using strict compatibility, please update your add-on to be compatible with Pale Moon's new milestone release. Thanks!

EDIT: Btw I was using your add-on with the install.rdf just changed to be compatible with version 32 when I was testing the 32.0 beta for the past couple of days, and it looks to be working fine for me. So you probably just need to change install.rdf.

**Comment by Gordon-Dry** [comment]
You can do it yourself quickly. XPI is a ZIP with different extension. Just edit the RDF und repack. Drag'n'drop into Pale Moon and you're good to go.

**Comment by GrahamFinch** [comment]
I tried doing that and it didn't work. I changed "31" to "32" and saved and...it went back to 31.
Am I missing something?

**Comment by martok** [comment]
Whoops, I knew I forgot something important :laughing:
Released 1.26.
