### ISSUE TITLE
Class and let for Firefox 42+

### ISSUE THREAD

**Issue by JeanPaulLucien** [martok/palefill#82]
Firefox below 45 version without Palefill reports:
```
SyntaxError: class is a reserved identifier
SyntaxError: let is a reserved identifier
```
Firefox 42-45 does not use these keywords. Status "Reserved" is not needed more. 
I would to discover a way to bring class and let features in Firefox 42+.

If anybody have an idea, I'm ready to test this attempt.

**Comment by martok** [comment]
> I would to discover a way to bring class and let features in Firefox 42+.

Easy: update Firefox.

Firefox is not supported by Palefill.

You wouldn't even be able to run Palefill without classes if it was.

**Comment by JeanPaulLucien** [comment]
> You wouldn't even be able to run Palefill without classes if it was.

I suspect that. :disappointed: 
@martok I consider your know more about Firefox XUL. What is your opinion about to add class and let support through addons? May it possible? One addon makes class and let workable, then install Palefill.
