### ISSUE TITLE
Support for AVM FRITZ!Box router's UI with new router firmware

### ISSUE THREAD

**Issue by Gordon-Dry** [martok/palefill#83]
Since the AVM FRITZ!Box routers get the latest firmware [7.50](https://en.avm.de/products/fritzos/fritzos-750/) they claim not supporting outdated browsers anymore:
![FRITZ!Box_-_2023-02-11_01 16 09](https://user-images.githubusercontent.com/29145213/218225338-e4e87997-6a0c-4b49-9447-d381b7aad8fa.jpg)

**Comment by Gittyperson** [comment]
Related:

https://forum.palemoon.org/viewtopic.php?f=70&t=28995

https://repo.palemoon.org/MoonchildProductions/UXP/issues/1240

**Comment by martok** [comment]
The original issue is solved, but since I've had the chance to play with an updated Fritzbox a few weeks ago and that doesn't alert on unsupported browsers, but instead just doesn't display the login window:

They now have the exact same buggy polyfill as #74. PM has everything they need, but their *feature test code* is buggy, which causes it to inject a `Promise` polyfill that doesn't contain `Promise.all()`. I've been trying to debug that for a few hours, but that didn't go anywhere other than increase my hate of Webpack.

**Comment by martok** [comment]
Resolved as [UXP#2436](https://repo.palemoon.org/MoonchildProductions/UXP/pulls/2436) by implementing one more Promise feature. Should be in the next release.

**Comment by Vangelis66** [comment]
@martok : Apologies for this OT, but I don't have an account in 

https://repo.palemoon.org/

or 

https://forum.palemoon.org/

to "properly" notify you; as the owner of this repo, you're free to DELETE this OT comment of mine after the needed info gets to you 😜 ...

> Resolved as [UXP#2436](https://repo.palemoon.org/MoonchildProductions/UXP/pulls/2436)

Well,  [UXP#2436](https://repo.palemoon.org/MoonchildProductions/UXP/pulls/2436) necessitated the implementation of [UXP#2435](https://repo.palemoon.org/MoonchildProductions/UXP/issues/2435); [UXP#2435](https://repo.palemoon.org/MoonchildProductions/UXP/issues/2435) itself required resolving [UXP#2240](https://repo.palemoon.org/MoonchildProductions/UXP/issues/2240), but that last one caused regressions/crashes described in [UXP#2452](https://repo.palemoon.org/MoonchildProductions/UXP/issues/2452) ...

The consensus among **MCP** devs is so far that these crashes are confined to the use of the legacy (XUL) version of the **NoScript** extension in **UXP**-based browsers; **Moonchild** would have [closed](https://repo.palemoon.org/MoonchildProductions/UXP/issues/2452#issuecomment-39674) [UXP#2452](https://repo.palemoon.org/MoonchildProductions/UXP/issues/2452) as a `wontfix`, but testimony has arisen from the `roytam1` fork users that at least one site is able to crash the browser (with **#2240** merged in) without ever having the **NS** extension installed: 

https://www.theregister.com/

You can read more [here](https://msfn.org/board/topic/184051-my-browser-builds-part-4/?do=findComment&comment=1258299) (MSFN) and [here](https://forum.palemoon.org/viewtopic.php?f=62&t=30769) (PMForums); as is the case for many years, **Moonchild** is [reluctant to accept any bug reports from the forks community](https://forum.palemoon.org/viewtopic.php?p=247657#p247657) 😞 ...

I see you have prepared [UXP#2459](https://repo.palemoon.org/MoonchildProductions/UXP/pulls/2459) to tackle [UXP#2452](https://repo.palemoon.org/MoonchildProductions/UXP/issues/2452): 

> The last commit specifically fixes a reentrancy crash issue in **XUL extensions** (**NoScript**, namely). The IDB cleanup event timing is technically wrong then, but ABL, eMatrix and Palefill all don't trip that code path, so it should very rarely be reached at all.

Well, can you replicate a crash in `xul.dll` when visiting 
https://www.theregister.com/
with #2240 merged in and, if yes, does #2459 alleviate that? 

The point of this OT post is that #2240-related crashes aren't uniquely tied to "evil" **NoScript** 😉 ...

Thanks again for all you have contributed thus far to the UXP-platform communities and more thanks for continuing to do so ❤️ ...

Kind regards.

**Comment by Gordon-Dry** [comment]
I don't see a proper solution.

I see the login screen with only the input field for the userid, but as there is no input field for the password no usability is gained.

**Comment by Gittyperson** [comment]
"Next release" is clearly mentioned two posts above. That would be Pale Moon 33.

**Comment by Gordon-Dry** [comment]
@Gittyperson 
I read  the post. I did not ask you. And you did not get the fact that it's not 100% clear so I asked. Asking is not a crime. So fuck off with your passive agressive selfish bullshit of kinda playing the moderator with a shitty attitude towards users who ask.

**Comment by Gittyperson** [comment]
Wow.

**Comment by martok** [comment]
This is not a kind of tone I will tolerate on my issue tracker. **Gordon-Dry** has been blocked from further posts.

---

The answer was in fact correct. Next release of UXP means next release of Pale Moon.
