### ISSUE TITLE
pleroma 2.5+: setLocaleMessage is not a function

### ISSUE THREAD

**Issue by roytam1** [martok/palefill#86]
it happens in its pleromaFE:
`21:20:54.704 TypeError: t.setLocaleMessage is not a function 1 app.4c23e08cf351a54f4177.js:1:95998`

**Comment by roytam1** [comment]
@martok for out-of-scope of this issue:

> I've heavily excecised this on win32 by running test262's "language" section and the best I can say is that it is feature-correct and doesn't crash. There seems to be a bug in the test runner (also on 32.0 and 32.1b3) that rarely causes some tests to break, so with 23k tests about 50 randomly have different (or no) results. Running only "language/statements" section looks good.

UXP#2148 doesn't completely solving the crash issue, some users of my builds encountering crashes within mozglue until I reverting UXP#2083-part4 and -part5 to have a stable runtime. don't know if this issue affects your testings in UXP#2155.

**Comment by martok** [comment]
> it happens in its pleromaFE: `21:20:54.704 TypeError: t.setLocaleMessage is not a function 1 app.4c23e08cf351a54f4177.js:1:95998`

Just from testing on a public instance: doesn't break anything as far as I can see? It looks like a normal bug in their code to me, since it throws the same in Chromium.

---

> UXP#2148 doesn't completely solving the crash issue, some users of my builds encountering crashes within mozglue until I reverting UXP#2083-part4 and -part5 to have a stable runtime. don't know if this issue affects your testings in UXP#2155.

If this is still an issue and you have either a stack trace or steps to repro, please report on RPMO. If not... not much we can do... :man_shrugging:
