### ISSUE TITLE
Glarysoft's homepage doesn't work properly

### ISSUE THREAD

**Issue by AstroSkipper** [martok/palefill#88]
The website of **Glarysoft** doesn't work properly in **New Moon 28** and **Serpent 52**. When you open the link https://www.glarysoft.com/, the buttons **Products**, **Downloads**, **Support** and **Company** don't work. It seems to be a **JavaScript** problem. Maybe, it can be polyfilled. More details and an output of the web console can be found here: https://msfn.org/board/topic/184051-my-browser-builds-part-4/?do=findComment&comment=1242435

Thanks in advance! Kind regards, AstroSkipper

**Comment by AroKol78** [comment]
![jestok1](https://user-images.githubusercontent.com/70756447/228840332-49638351-73af-4e48-93ac-ab0a81a6af71.JPG)

**Comment by AstroSkipper** [comment]
Thanks AroKol78 for your reply and image! Issue solved! The problem was **uBlock Origin**, which blocked the **addthis.com** page. This issue can be closed now,

**Comment by AroKol78** [comment]
works for me with `addthis.com` disabled
![noniewiem](https://user-images.githubusercontent.com/70756447/228876527-875cb7f7-3405-4efa-bfbd-788f22eb569c.JPG)

**Comment by AstroSkipper** [comment]
> ... And since you were the **one that submitted it**, can you not close it **yourself**, please? 😉
> 
> Thanks and regards 😄 ...
I totally overlooked that I am able to close it by myself.
