### ISSUE TITLE
AudioWorklet polyfill

### ISSUE THREAD

**Issue by roytam1** [martok/palefill#93]
regarding #92, there is polyfill available:
https://github.com/GoogleChromeLabs/audioworklet-polyfill

and PM forum member tested working: https://forum.palemoon.org/viewtopic.php?p=244471#p244471

(I can't comment in original issue since it is locked)

**Comment by martok** [comment]
Tag #92.

Thanks, that works.

> (I can't comment in original issue since it is locked)

I really wish Github had any kind of community moderation tools with better granularity than "Block user from everything I've ever done" and "Ban everyone from commenting". It's been 15 years, people.

**Comment by NS-Clone** [comment]
> I really wish Github had any kind of community moderation tools

there is offtop about "howto make similar GreaseMonkey script"
and because i'm not native english speaker
i can't ask in english about some things...
