### ISSUE TITLE
Wont install

### ISSUE THREAD

**Issue by billmcct** [martok/palefill#98]
Pale Moon will not install the file . Says it seems to be corrupted.

**Comment by martok** [comment]
Works here.
That is however the exact error message I get when I click the link in Firefox?

More information please (version, installation method, ...)

**Comment by billmcct** [comment]
Sorry, I was still on 32.5.1. I didn't realize there was a new version 32.5.2. Updated and it installed just fine. As for installing, I tried to install directly from GitHub and by drag and drop.

**Comment by martok** [comment]
That should not matter - all the addon declares is that it wants anything between 28.10.0 and the upcoming 33.0.
But if it works it works, so that's great 👍
